# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: akshat.saini@axleinfo.com
author_name: Akshat Saini
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: server
labextension_name: polus-render
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: polus_render
repository: ''
test: true
viewer_name: ''

