name: Build

on:
  push:
    branches: master
    paths:
      - "jupyterlab_wipp/**"
      - "jupyterlab_wipp_plugin_creator/**"
    
  pull_request:
    branches: '*'
    paths:
      - "jupyterlab_wipp/**"
      - "jupyterlab_wipp_plugin_creator/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14.x'
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install dependencies
        run: python -m pip install -U jupyter_packaging~=0.10.4 jupyterlab~=3.0.16 pip wheel 
